# 生產模式多階段建置
# 1. 建置階段
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2. 服務階段 (使用輕量級 Nginx 提供服務)
FROM nginx:alpine AS production
# 移除預設配置並複製自定義配置
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
# 複製建置好的靜態文件
COPY --from=build /app/dist /usr/share/nginx/html
# 80 是 Nginx 預設端口
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
